controller_list:
  - name: fake_base_controller
    joints:
      - basex_joint
      - basey_joint
      - basepsi_joint
  - name: fake_right_arm_controller
    joints:
      - torso_lift_joint
      - r_shoulder_pan_joint
      - r_shoulder_lift_joint
      - r_upper_arm_roll_joint
      - r_elbow_flex_joint
      - r_forearm_roll_joint
      - r_wrist_flex_joint
      - r_wrist_roll_joint
  - name: fake_left_arm_controller
    joints:
      - torso_lift_joint
      - l_shoulder_pan_joint
      - l_shoulder_lift_joint
      - l_upper_arm_roll_joint
      - l_elbow_flex_joint
      - l_forearm_roll_joint
      - l_wrist_flex_joint
      - l_wrist_roll_joint
  - name: fake_whole_right_controller
    joints:
      - basex_joint
      - basey_joint
      - basepsi_joint
      - torso_lift_joint
      - r_shoulder_pan_joint
      - r_shoulder_lift_joint
      - r_upper_arm_roll_joint
      - r_elbow_flex_joint
      - r_forearm_roll_joint
      - r_wrist_flex_joint
      - r_wrist_roll_joint
  - name: fake_whole_left_controller
    joints:
      - basex_joint
      - basey_joint
      - basepsi_joint
      - torso_lift_joint
      - l_shoulder_pan_joint
      - l_shoulder_lift_joint
      - l_upper_arm_roll_joint
      - l_elbow_flex_joint
      - l_forearm_roll_joint
      - l_wrist_flex_joint
      - l_wrist_roll_joint
  - name: fake_right_arm_only_controller
    joints:
      - r_shoulder_pan_joint
      - r_shoulder_lift_joint
      - r_upper_arm_roll_joint
      - r_elbow_flex_joint
      - r_forearm_roll_joint
      - r_wrist_flex_joint
      - r_wrist_roll_joint
  - name: fake_left_arm_only_controller
    joints:
      - l_shoulder_pan_joint
      - l_shoulder_lift_joint
      - l_upper_arm_roll_joint
      - l_elbow_flex_joint
      - l_forearm_roll_joint
      - l_wrist_flex_joint
      - l_wrist_roll_joint
  - name: fake_right_ee_group_controller
    joints:
      - r_gripper_l_finger_joint
      - r_gripper_motor_slider_joint
      - r_gripper_motor_screw_joint
      - r_gripper_joint
  - name: fake_my_right_arm_controller
    joints:
      - r_shoulder_pan_joint
      - r_shoulder_lift_joint
      - r_upper_arm_roll_joint
      - r_elbow_flex_joint
      - r_forearm_roll_joint
      - r_wrist_flex_joint
      - r_wrist_roll_joint